### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rileylark** [rooklift/sgf_to_gif#9]
Hey there,

I'm interested in using your code to generate gifs from SGF files. Is that alright?

Thanks,
Riley

**Comment by rooklift** [comment]
In what context?

**Comment by rileylark** [comment]
Right now just goofing around making a toy cloud function to generate gifs from SGF files. Maybe in the future offering the code to online-go.com or similar services, but I am not affiliated with any of those in any serious way (I am a customer of online-go.com and submitted one 30-line patch to their client code).

I wouldn't want to do anything with your work that you didn't want. Would you be willing to choose a standard license to communicate your preferences?

**Comment by rooklift** [comment]
I'll go with the same license as online-go then.

**Comment by rileylark** [comment]
Thanks! The clarity helps a lot!
